---
- name: Update i1 server
  hosts: i1

  tasks:
   - name: create Directory
     file:
       path: /home/centos/n3_dir
       state: directory

  tasks:
   - name: create Directory
     file:
       path: /home/centos/n3_dir_1
       state: directory

  - name: Update i2 server
    hosts: i2

    tasks:
      - name: create Directory
        file:
          path: /home/centos/n3_dir_1
          state: directory

    tasks:
     - name: create Directory
       file:
         path: /home/centos/n3_dir_2
         state: directory
   

- name: Update group1 server
  hosts: g1

  tasks:
   - name: create Directory
     file:
       path: /home/centos/n3_dir_group1
       state: directory

  tasks:
   - name: create Directory
     file:
       path: /home/centos/n3_dir_group2
       state: directory
...
