---
- name: Install httpd 
  hosts: i2
  become: yes

  tasks:
   - name: install HTTPD
     yum:
       name: httpd
       state: present

  tasks:
   - name: start HTTPD
     service:
       name: httpd
       state: started

  tasks:
   - name: enable HTTPD
     service:
       name: httpd
       enabled: yes
...
