---
- name: Install httpd 
  hosts: p2
  become: yes

  tasks:
   - name: install Apache-2
     apt:
       name: apache2
       state: present

   - name: start Apache-2
     service:
       name: apache2
       state: started

   - name: enable Apache-2
     service:
       name: apache2
       enabled: yes
...
