---
- name: Updating to maintainence page 
  hosts: g1
  become: yes

  tasks:
   - name: update maintainence
     template:
       src: host_and_ip.j2
       dest: /var/www/html/host_and_ip.html
...
