---
- name: Updating to maintainence page 
  hosts: g1
  become: yes
  vars:
    http_port_default: 80
    http_port_1: 2030
    http_port_2: 4550

  tasks:
   - name: update maintainence
     template:
       src: httpd.j2
       dest: /etc/httpd/conf/httpd.conf

  - name: restart
     service:
       name: httpd
       state: restarted
...
