---
- name: Updating to maintainence page 
  hosts: g1
  become: yes
  vars:
    myname: hemanth
    ip-1: 2020
    ip-2: 2030
    ip-3: 4550

  tasks:
   - name: update maintainence
     template:
       src: httpd.j2
       dest: /etc/httpd/conf/httpd.conf
...
